"""Workout table complete version, dicts added

Revision ID: 475d96e77931
Revises: 1d1769f04d6b
Create Date: 2026-09-03 11:40:25.457067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475d96e77931'
down_revision = '1d1769f04d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WorkoutExercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['Exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['Workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Workout', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('duration_minutes')

    op.drop_table('WorkoutExercise')
    # ### end Alembic commands ###
